### ISSUE TITLE
Env file is not being written to zshrc

### ISSUE THREAD

**Issue by jlibermann** [panoptes/POCS#1005]
**Describe the bug**
The `env` file is not being written to `~/.zshrc` in the `install-pocs` script. 

**To Reproduce**
1. Run `install-pocs`
2. `vim ~/.zshrc`
3. See error.

**Additional context**
I recently installed `zsh` and `oh my zsh` on my local.

**Comment by wtgee** [comment]
Hm, thanks for reporting.  I think we might go toward relying on the user to populate a `.env` file but not sure.  Will know within a day or two as these PRs move their way through the system. I'll leave this open for now.

Thanks!
