### ISSUE TITLE
`camera.take_observation` does not implicitly record field coordinates

### ISSUE THREAD

**Issue by danjampro** [panoptes/POCS#1019]
Currently, the observation status headers are parsed to `camera.take_observation` by calling `observatory.get_standard_headers` beforehand, which records important information like `RA-MNT` and `DEC-MNT`. However, if `camera.take_observation` is called without parsing these headers, no information about the ra/dec of the `Field` gets recorded in the FITS headers, meaning there is no way to tell what the telescope was (meant to be) looking at, despite that information being already available from within `camera.take_observation`.

My code enhancement suggestion would be to add field information to the header implicitly from within `take_observation`, making use of the `Observation.Field`.

Code: https://github.com/panoptes/POCS/blob/f8e3dc6306dc68022d55014a3cccbae4a3ec3e60/src/panoptes/pocs/observatory.py#L617

**Comment by wtgee** [comment]
See also #1002
