### ISSUE TITLE
Simulated DSLR camera clears exposure event before FITS file is written (bug)

### ISSUE THREAD

**Issue by danjampro** [panoptes/POCS#1022]
This bug causes a minor delay between ending the exposure and writing the FITS file, which leads to errors.

Code:
https://github.com/panoptes/POCS/blob/804e48d3e66fb6d413aef6ac2f675349bcd0f819/src/panoptes/pocs/camera/simulator/dslr.py#L58

**Comment by wtgee** [comment]
That code doesn't point to where the problem is. @danjampro can you provide more details?
