### ISSUE TITLE
SDK cameras no longer working

### ISSUE THREAD

**Issue by AnthonyHorton** [panoptes/POCS#1025]
**Describe the bug**
Changes to the camera base class have stopped the SDK cameras (ZWO, FLI, SBIG) from working.

**To Reproduce**
1. Attempt an instance of an SDK `Camera` class
2. See errors due to attempts to assign to read-only `is_exposing` property

**Expected behavior**
SDK camera instances can be created and used.

**Additional context**
The root cause of this problem is changes to the camera base class (and DSLR camera class, and camera simulator) to use the `is_exposing` property as an alias for `_is_exposing_event,is_set()`, and, more specifically, using assignment to `is_exposing` to set/clear this event. For the DSLRs this property is read only, and directly tracks the internal state of the camera hardware.

**Comment by wtgee** [comment]
Closed by #1026. Further problems should open a new Issue.
