### ISSUE TITLE
Exposure readout_thread is not accessible.

### ISSUE THREAD

**Issue by danjampro** [panoptes/POCS#1031]
The readout thread is not accessible from outside of `take_exposure`. This means it is impossible to consistently wait for a non-blocking exposure to finish reading out. 
Code:
https://github.com/panoptes/POCS/blob/d8e69ae2e8012009f59decf45f9a121588735839/src/panoptes/pocs/camera/camera.py#L507
Suggested change:
Return the readout event rather than `is_exposing_event`.

**Comment by wtgee** [comment]
Closed by #1032
