### ISSUE TITLE
create_scheduler_from_config should take an optional config argument

### ISSUE THREAD

**Issue by danjampro** [panoptes/POCS#1057]
https://github.com/panoptes/POCS/blob/806fd13d54d028c59225e003c759c33b65a22639/src/panoptes/pocs/scheduler/__init__.py#L19

Also true of the mount: 

https://github.com/panoptes/POCS/blob/f8e3dc6306dc68022d55014a3cccbae4a3ec3e60/src/panoptes/pocs/mount/__init__.py#L15

**Comment by wtgee** [comment]
See also #1087
