### ISSUE TITLE
Make install of software as simple as possible.

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#115]
Related:

- [x] #94
- [x] ~~#27~~
- [x] #77 
- [ ] #87 
- [x] #26
- [x] #97

**Comment by jamessynge** [comment]
See https://github.com/jamessynge/POCS/tree/install where I'm working on an install script.

**Comment by wtgee** [comment]
#77 and #87 will still apply, but this will be closed by #951.

**Comment by wtgee** [comment]
Mostly replaced by the guide at projectpanoptes.org
