### ISSUE TITLE
Don't download IRES files every time tests are run

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#121]
In general we need a better mechanism for checking if these are outdated. The [astroplan documentation](https://astroplan.readthedocs.io/en/latest/) might provide clues as to the best way to achieve this.

**Comment by jamessynge** [comment]
Let's consider changing utils/data.py to download the file at most every week (for example), storing a copy in /var/panoptes/data whose date it can check.

**Comment by wtgee** [comment]
We can do this but I think that we also want to just install a cron job that performs this action once per week regardless. Could actually be a part of #129 when installed for normal units.
