### ISSUE TITLE
POCS install: fails to install astrometry-net

### ISSUE THREAD

**Issue by oguyon** [panoptes/POCS#1212]
Log shows:
E: Unable to locate package astrometry-net

Consequently, subsequent packages fail to install, as this command fails:

  sudo apt-get -y -qq install \
    ack \
    astrometry-net \
    astrometry-data-tycho2-10-19 \
    byobu \
    curl \
    dcraw \
    exiftool \
    fonts-powerline \
    gcc \
    htop \
    httpie \
    jo \
    jq \
    libcfitsio-bin \
    make \
    nano \
    vim-nox \
    supervisor \
    wget

**Comment by wtgee** [comment]
Thanks, that would do it. I've put in a fix at #1213.  We can also add an `--ignore-missing` option but I think I would rather it complain more loudly than fail silently.
