### ISSUE TITLE
Write documentation (a manual) for operating a Panoptes unit

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#135]
After a team has built a Panoptes unit, they need guidance about how to operate it, including polar alignment.

For reference, here are some examples I came across:

1. https://www.ctio.noao.edu/DocDB/0008/000801/001/aTmCam%20User%20Manual.pdf
2. http://gtn.sonoma.edu/gort/operators/op_instructions.php

**Comment by wtgee** [comment]
This is somewhat a WIP but a lot has been done.  If you are a builder and find this issue, ask on the forum for documents:  https://forum.projectpanoptes.org.

Closing generic issue. New issues should identify specific updates.
