### ISSUE TITLE
Change rs232.SerialData to deal with bytes, not characters in a charset

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#161]
Leave it up to the caller to know whether it is dealing with a character stream, line stream or byte stream.

Address this soon after PACE and PEAS merged into POCS.

**Comment by wtgee** [comment]
@jamessynge  Didn't this happen? I can't seem to find the PR.

**Comment by jamessynge** [comment]
No, not yet. We don't yet have PEAS tests running in POCS, which made me reluctant to change that. We need a trivial Arduino sketch simulator (e.g. emits appropriate json every couple of seconds).

**Comment by wtgee** [comment]
I want to say this has happened now. :) @jamessynge ?

**Comment by wtgee** [comment]
Ping @jamessynge

**Comment by jamessynge** [comment]
Closing as obsolete. We're not running into a problem with this.
