### ISSUE TITLE
Figure out appropriate behavior if device is not found at startup

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#185]
rs232.SerialData doesn't require that the device exist at startup, which seems generally appropriate (e.g. if restarting after a power outage, we want POCS to start even if one device is not currently powered, or is slow to startup). But this means we need some means of validating that either the port is valid, e.g. can be opened, is a well formed /dev/tty path, or has been previously validated.

**Comment by wtgee** [comment]
@jamessynge has this been solved?

**Comment by kmeagle1515** [comment]
https://github.com/panoptes/POCS/blob/11a181c191278bb36cf186713ef8ec7289955130/pocs/utils/rs232.py#L168
@wtgee i guess this issue is already solved

**Comment by wtgee** [comment]
Closing as stale.
