### ISSUE TITLE
Adjust dome API

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#189]
Based on feedback / discussion in PR #188:
- Rename state to status.
- Remove _is_connected from AbstractDome.

**Comment by wtgee** [comment]
* `status` should be a method, not a property, to maintain consistency with all other hardware.
* `Observatory.open_dome()` and `Observatory.close_dome()` do not need to exist

**Comment by wtgee** [comment]
@jamessynge I believe these have been taken care of. Request to remove `open_dome` and `close_dome` withdrawn.

**Comment by jamessynge** [comment]
#587 opened to track the remaining issue.
