### ISSUE TITLE
PanMessaging.send_message doesn't ensure channel name has no space in it.

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#205]
PanMessaging.receive_message requires that it be able to split the received message into a channel name and a json encoded message body.

We should change the top-level encoding used to be a json encoded list of two elements, the channel name and the dict containing the structured message.

**Comment by wtgee** [comment]
@jamessynge, you did some recent work with the messaging. Could you speak to any update on this Issue?

**Comment by wtgee** [comment]
Ping @jamessynge

**Comment by jamessynge** [comment]
Not done. Minimal change would of course be to just throw an exception if there is a space in the name.

**Comment by wtgee** [comment]
Was closed by #593.
