### ISSUE TITLE
Fix make_pretty_image for FITS files

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#232]
Image currently doesn't show anything and is far from pretty. Need to change the private function [`_make_pretty_from_fits`](https://github.com/AstroHuntsman/POCS/blob/develop/pocs/utils/images.py#L477).

See also #43

**Comment by wtgee** [comment]
#319 in progress.

**Comment by jermainegug** [comment]
#319, I believe is ready to be merged.
