### ISSUE TITLE
Link focusing images to latest.jpg

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#235]
Would be nice to see the focusing as it changes. Would only happen for primary camera without some work.

**Comment by wtgee** [comment]
@jermainegug this might be an easy one to pick off in some of your sleepless nights :)

**Comment by jermainegug** [comment]
@wtgee sounds good :)

**Comment by wtgee** [comment]
Actually it's not entirely obvious what we want to see here. @AnthonyHorton, any input?

**Comment by AnthonyHorton** [comment]
Hmmm, most useful would probably be the `*_final.fits` image that gets taken once the autofocus thinks it's finished.  Would be nice to be able to confirm at a glance that a decent focus was obtained.

The other images get superceded so quickly (for broadband filters, at least) they'd be gone before PAWS updated.

**Comment by wtgee** [comment]
But which of the cameras would we want to view this for? Ideally we just modify it to get links for all of them I suppose, but that is more work.

**Comment by AnthonyHorton** [comment]
Yes, ideally you'd check all the cameras, but that would be more work. Question is whether it would be worth it? Depends on how often there are going to be issues with focusing. Working on that...

**Comment by wtgee** [comment]
This was completed at some point.
