### ISSUE TITLE
Save the config in a local file

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#238]
As per the comments in https://github.com/panoptes/POCS/pull/216, the `pocs.utils.config.save_config()` function should not override the built-in config but default to saving with `_local.yaml`.

**Comment by jermainegug** [comment]
Is this what we are looking for?

**Comment by jermainegug** [comment]
@wtgee just quickly fixed and tested the code I just wrote up, works as requested. Did you want me to start a PR so you can review it?

**Comment by wtgee** [comment]
This has been fixed (and moved to) `panoptes-utils`.
