### ISSUE TITLE
Remove PanLogger class

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#253]
PanLogger exists to handle formatting in the more modern Python style, but it turns out that Python's logging.Formatter class takes a style kwarg on the ctor which controls whether legacy or modern formatting is used. The benefit of using a "real" logger is that the source (file name and line number) of the log messages should then be correct, and not always in pocs/utils/logger.py.

**Comment by wtgee** [comment]
Make PR #254, which should accomplish the above. Note that merely using the `style` keyword does not achieve what we were looking for, which was why we didn't just use that in the first place. The `style` keyword on the ctor only affects the log format string (i.e. the `'%(asctime)s - %(message)s'`) but not the actual interpolation on the `message`
