### ISSUE TITLE
shapely missing from install

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#255]
Looking up how to install, I came across a choice between `shapely` and `shapely[vectorized]`, where the latter requires numpy, which we also require.

**Comment by jamessynge** [comment]
Actually, its missing from the install for POCS, and is required by PIAA. But, I'd like to have a single install script for the software needed for a unit.

**Comment by wtgee** [comment]
This should be closed with movement of polar_alignment code to POCS itself.
