### ISSUE TITLE
Supervisord

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#26]
Review supervisord scripts and make sure we are starting all items appropriately.
- [ ] Weather scripts (#25)
- [ ] Sensors scripts (#25)
- [ ] PAWS site
- [ ] Unit script
- [ ] Other? (e.g. maintenance scripts, data processing, updating, etc.)

**Comment by wtgee** [comment]
We need to review this and see if it is what we want. The idea was to have these items start up automatically after reboot. However it seems like reboots should only happen manually in which case the user wants to probably start things up manually (maybe with one simple command). If a reboot happens unexpectedly we should probably alert the user somehow and allow them to inspect the system before start things.

**Comment by jamessynge** [comment]
I'd like a full startup script, with flags to control what is attached, and then the user can decide whether to run that script automatically at boot. For manual control, perhaps we could have it start a screen or tmux session, with separate "window" for each of the shells that needs to be executed (e.g. peas_shell).

**Comment by wtgee** [comment]
Closing this as stale.
