### ISSUE TITLE
PAWS needs requirements.txt

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#273]
Tornado required, but not installed by POCS install-dependencies.sh

**Comment by wtgee** [comment]
This is listed in https://github.com/panoptes/PAWS/blob/develop/requirements.txt. The install-dependencies.sh should not be duplicating these, it should just be cloning the repo then running `pip install -r requirements.txt`.

**Comment by jamessynge** [comment]
Oops, my mistake, my PAWS clone wasn't up to date apparently.
