### ISSUE TITLE
Verify that Arduino sketches can build

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#283]
The Travis CI build tests that pocs works, but not that we can build the Arduino sketches. We should fix that. As of Arduino 1.5, the Arduino IDE has a command-line mode where it can verify (compile) or upload sketches. For example, this works on my laptop (following PR #282):
```bash
/home/james/tools/arduino-1.8.2/arduino \
    --verify --board arduino:avr:micro \
    resources/arduino_files/camera_board/camera_board.ino 
```

**Comment by wtgee** [comment]
Yes, good idea. Examples [here](https://learn.adafruit.com/continuous-integration-arduino-and-you/testing-your-project).
