### ISSUE TITLE
Camera Simulator

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#29]
Camera simulator needs to be able to produce images, including pointing images (ideally with some offset). Need a folder of test images to work with this.

**Comment by joshwalawender** [comment]
One way to do this without needing a folder of images, would be to have a tool which would generate an "image" by dropping gaussian stars down based on catalog positions.  Something like this might already exist, so it would be worth looking around for one.

**Comment by joshwalawender** [comment]
Here's something that looks like it might do the trick.  It's from the same developer as SExtractor.
http://www.astromatic.net/software/skymaker

**Comment by wtgee** [comment]
Nice, thanks. We can either use this or one or two real images. We just
need to be able to plate solve them then move them a tiny bit to check
tracking/pointing etc.

Hopefully I'll be getting to this soon.

On Thu, May 12, 2016 at 9:31 AM, Josh Walawender <notifications@github.com>
wrote:

> Here's something that looks like it might do the trick. It's from the same
> developer as SExtractor.
> http://www.astromatic.net/software/skymaker
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/panoptes/POCS/issues/29#issuecomment-218861642>
>



-- 
~Wilfred Tyler Gee

**Comment by wtgee** [comment]
There are currently some dummy images in the test folder (`$POCS/tests/data`) and the camera simulator will just always use these as a file name. This allows for unning of the entire machine with a camera simulator. Additional features should be defined separately.
