### ISSUE TITLE
Add type annotations to python code

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#298]
Per our discussion in closed PR #207, I'd like to experiment with adding type annotations, both as documentation and to improve the code quality. It can be helpful during this process to change the code so that the types are clearer.

The downside is that the type annotations can make the code rather verbose compared to regular python without type declarations, thought that is partially addressed by code changes to introduce new & simpler types (e.g. instead of Dict(String, Union(Number, String, Foo, Bar)), we can simplify the annotations or introduce new classes).

**Comment by wtgee** [comment]
We've decided to not pursue this option for now. Closing issue.
