### ISSUE TITLE
Explore use of JSON library for arduino

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#310]
Our JSON handling is kind of clunky and makes us have to manage commas and other strings in weird ways. We should explore the use of a library such as https://github.com/bblanchon/ArduinoJson

Related: #309

**Comment by jamessynge** [comment]
I was thinking of writing something simple for JSON serialization, but ArduinoJson looks like it covers all the bases, and then some!

**Comment by wtgee** [comment]
I don't think it was that developed a year or so ago when I last checked but looks pretty nice now.

We could consider using json for input as well. (Now that you've written the nice input handlers. :smiley:)

**Comment by wtgee** [comment]
Will be closed by #860
