### ISSUE TITLE
Reconcile baudrate differences

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#312]
The Arduino sketches setup their serial ports at 9600 buad, while rs232.SerialData defaults to 115200 (and is not overridden). I suspect communication is working because we're using Serial over USB, so the baudrate probably doesn't matter.

**Comment by wtgee** [comment]
Actual solution to whatever we figure out should be part of #181.

**Comment by jamessynge** [comment]
For now, this is addressed by hard coding baudrate=9600 in sensors.py.
