### ISSUE TITLE
Temperatures not reading on PAN001

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#316]
The DS18B20s are not reading on the telemetry board after updating to most recent code. Perhaps related to #311

**Comment by jamessynge** [comment]
I'll make up a board with a couple of the temp sensors so that I can validate the code.

**Comment by wtgee** [comment]
I am going to try and adapt the trucker board to the shared libraries in which case I have a board already built up to test. Will see if I can do this weekend.

**Comment by wtgee** [comment]
Definitely part of #311. The compilation warnings relate to a section of the code that is printing the resolution for the DHT as part of `PrintDeviceInfo`. I simply commented out that line and compilation worked without complaints. Uploading to telemetry board then gets me temperature (and current) readings.

Closing as non-issue in favor of fixing #311
