### ISSUE TITLE
Prevent Arduinos from locking up

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#318]
I screwed something up with the telemetry board on PAN006 a while agosuch that it wouldn't respond.
This should be fixed in current code, but it would be a good idea to keep ourselves from screwing up. One solution is a watchdog timer. See: https://tushev.org/articles/arduino/5/arduino-and-watchdog-timer

According to that page, this code would trigger a reset if loop() doesn't run every 8 seconds:
```c++
#include <avr/wdt.h>
void setup(){
wdt_enable(WDTO_8S);
}
void loop(){
//do stuff here
wdt_reset();
}
```

**Comment by wtgee** [comment]
I played with the watchdog timer in the beginning (three years ago) and seem to remember I couldn't get it to work on the micro. Worth exploring again though.

**Comment by kmeagle1515** [comment]
@jamessynge @wtgee for timer specific threshold values are available. That mainly depends upon our requirement. So what threshold should be ideal for our system?
