### ISSUE TITLE
Mongo db name incorrect

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#324]
Things are going into a db named `db` rather than what is in the config.

**Comment by wtgee** [comment]
I think this answers this question: https://github.com/panoptes/POCS/blob/0d6f5ab84067070cc1bdf400e170218c00e4f59e/pocs/utils/database.py#L60

**Comment by wtgee** [comment]
^^ Hey, that's a snazzy new github feature when you refer to a line. :)

**Comment by jamessynge** [comment]
Thanks. We probably need a comment explaining the indirections used in that class.
