### ISSUE TITLE
Incorporate trim rates in RA and Dec based on pointing/tracking model

### ISSUE THREAD

**Issue by joshwalawender** [panoptes/POCS#33]
Based on feedback, set or update a "trim rate" on the RA and Dec tracking rates.  The goal is to maintain the position of the stars on the pixel grid to sub-pixel accuracy over the duration of an observation (many images).

One way to generate the feedback is to only look at pointing errors, then make a physical model of the mount.  This is the traditional way of doing this.  In the earlier version of the prototype @oguyon did this differently.  He measured the offset between subsequent images (via cross correlation) and estimated a tracking rate error for that position in mount coordinates (HA and Dec).  With a sufficient number of these points, he fit a polynomial to the data to create the model.  Then each time a target was slewed to, he evaluated this model and applied the appropriate trim rates.  I tend to prefer this method as easier to understand than the physical model which was often modified by arbitrary polynomials anyway, so it wan't very physical.

There are also a few ways we might input these trim rates.  First, we could use mount commands (either direct serial commands or via an INDI layer).  Second, we could use the arduino in the electronics package to make "guiding" corrections to the mount.  The rate correction would basically be a PWM signal output by the arduino to the mount guide inputs.

**Comment by wtgee** [comment]
This is called from the Analyzing state. See:

https://github.com/panoptes/POCS/blob/develop/pocs/state/states/default/analyzing.py#L11
