### ISSUE TITLE
Add a utility program for listing info about hardware

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#339]
List camera, Arduinos, mount, dome. Print status, port, serial numbers, etc., as appropriate.

**Comment by jamessynge** [comment]
Wilfred suggested:

FWIW, and regarding comment (#320) above about separate utils for discovering devices, I have mostly been avoiding making the module callable via `if __main__` _unless_ they are in the utils folder. However, that would make development a little annoying as you would have to run a util file to test the sensors file.  Still, could end up looking something like:
```
python pocs/utils/devices.py --list_arduinos
python pocs/utils/devices.py --list_cameras
python pocs/utils/devices.py --list_attached_hardware
```
etc.

**Comment by wtgee** [comment]
Could also be a part of https://github.com/panoptes/panoptes-tutorials/issues/48
