### ISSUE TITLE
Document how to upload to Arduinos from Linux

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#343]
User needs permission to use device (e.g. /dev/ttyACM0).
May need to remove modem manager: `sudo apt-get purge modemmanager`
There is advice on arduino.cc regarding using Linux for Arduino development, and we should provide pointers to that.

**Comment by kmeagle1515** [comment]
hello sir!
Where will the documentation be included, in **README** or you want it in a different folder?

**Comment by kmeagle1515** [comment]
I have made a pr please review it.

**Comment by AnthonyHorton** [comment]
@kmeagle1515 For future reference, you should link related Issues and Pull Requests. Just use the Issue/PR number in the description or a comment and GitHub will automatically convert it to a link, e.g. the PR you're referring to here is #802.  Note, this *doesn't* work if you only do it in the title (as in your PR).

**Comment by wtgee** [comment]
> @kmeagle1515 For future reference, you should link related Issues and Pull Requests. Just use the Issue/PR number in the description or a comment and GitHub will automatically convert it to a link, e.g. the PR you're referring to here is #802. Note, this _doesn't_ work if you only do it in the title (as in your PR).

And we actually just added PR templates as part of #156.

**Comment by kmeagle1515** [comment]
@jamessynge  @wtgee this issue has been solved #802 .
