### ISSUE TITLE
pocs_shell shutdown POCS when asked to go_home

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#381]
I executed setup_pocs, unpark and go_home commands, the latter of which detected that the weather was not safe, and so shutdown POCS. That seems like an excessive reaction, and that it should actually park in that condition, but leave pocs setup.

Weather conditions at PAN006 were cloudy, but PAN006 is in closed a dome, so it was actually safe. It might be nice to add an option for domed installations to consider the weather safe if the dome is closed... it needs to be an option because some enclosures might not have room for the mount to leave the parked position without colliding with the enclosure (think low roll-off roof).

**Comment by wtgee** [comment]
Closing as stale.
