### ISSUE TITLE
Accelerometer Positioning

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#39]
We want to be able to recover the pointing position of the mount based on the accelerometer readings located inside the camera box. Various ways to do this exist. See e.g. (in no particular order):

http://perso-etis.ensea.fr/~pierandr/cours/M1_SIC/AN3397.pdf
http://arxiv.org/abs/1407.0035
http://www.it.bton.ac.uk/staff/gw4/papers/Displacement%20from%20Accelerometer.pdf

Values are available directly off the accelerometer (stored in mongodb locally) or off BigQuery. Values take the form:

``` json
                "camera_box" : {
                        "accelerometer" : {
                                "o" : 7,
                                "x" : -0.96,
                                "z" : -0.16,
                                "y" : -0.15
                        }
                }
```

where `o` represents the orientation (which can determine which side of the pier the accelerometer currently is)

See also #41 as we want to switch how we are reading the data as well.

**Comment by astroblogweb** [comment]
Is this issue still open? Can I work on the python code for it?

**Comment by joshwalawender** [comment]
Hi @astroblogweb , we have a summer intern who is just starting today and will be working on this topic.  Perhaps we can find another area yoiu might be interested in, or perhaps you can work together on it.  @wtgee coordinates all our software and he is away at a conference this week, so we might be a bit slow replying here for the next few days.

**Comment by wtgee** [comment]
Currently not recommending the accelerometer in the build so closing this as stale.
