### ISSUE TITLE
End of night shutdown

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#390]
At the end of the night the scheduler is not finding any valid observations, which is okay, but the system sort of treats this as an error and shuts down. This triggers a  "error" shut down that stops the state machine, meaning it won't come up automatically the next night. Output from logs is here:

```
I0118 15:41:30.891 messaging.py:122     PANCHAT Weather is good and it is dark. Something must have gone wrong. Stopping loop
I0118 15:41:30.892 machine.py:171       Stopping POCS states
```

See also #373

**Comment by jamessynge** [comment]
Thanks for filling this. I noticed that message this morning and wondered what was going to happen tonight.

**Comment by wtgee** [comment]
The problem ultimately comes from a `should_retry` counter that is part of [core.py](https://github.com/panoptes/POCS/blob/develop/pocs/core.py#L120). This defaults to 3 and is checked in the [sleeping state](https://github.com/panoptes/POCS/blob/develop/pocs/state/states/default/sleeping.py#L8). It was added earlier because some minor tracking errors (a no solve-field IIRC) were causing the unit to park itself but then it would waste the rest of the night sleeping.

In this situation, if `NoObservation` is found early enough it will send to sleep, but will retry to start up again. After three attempts it will think something is "really" wrong so `stop_states`.

You will have to `Ctrl-C` and start again as the entire state machine has been stopped. 

Could be worked around in a couple of ways.
