### ISSUE TITLE
Change Horizon constraint to allow loading from lists

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#394]
We currently restrict it to a list of tuples of tuples but that makes writing it in yaml less intuitive. Should be fine to accept a list of lists of list. :)

i.e. now only:
```
[
        ((40, 45), (50, 50), (60, 45))
]
```

but should accept:
```
[
        [[40, 45], [50, 50], [60, 45]]
]
```

**Comment by jermainegug** [comment]
We can now use a list of lists for our obstructions. :)

**Comment by wtgee** [comment]
> We can now use a list of lists for our obstructions. :)

Does this mean a PR is coming? :) I don't think I changed it yet.
