### ISSUE TITLE
Specify constraints in config file

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#402]
The constraints to use are currently hard-coded into the `Observatory` class but need to come from a config file. This would like be part of the move to dependency injection on part of the scheduler.

**Comment by jermainegug** [comment]
How are they hard-coded into the `Observaory` class? (Not questioning you, just not sure how to spot this myself)

**Comment by wtgee** [comment]
When an `Observatory` object is created it calls out `_create_scheduler`, which has the constraints hard-code [here](https://github.com/panoptes/POCS/blob/develop/pocs/observatory.py#L786). The idea would be to have a list of the constraint names under the `scheduler` key in the config file and then to use the `load_module` (see  [`_create_mount`](https://github.com/panoptes/POCS/blob/develop/pocs/observatory.py#L619) for an example of using this.)

**Comment by wtgee** [comment]
Not that you need the names and potentially any options in the config so might be a little tricky.

**Comment by jermainegug** [comment]
```
constrains = load_module(
                    'pocs.scheduler.{}'.format(constraint))
```
Do I want to do something like this?

**Comment by jermainegug** [comment]
Quite lost with this at the moment, not sure how to do it. Can't understand how `_create_module` works.

**Comment by wtgee** [comment]
Ok, I wouldn't worry about this for now. We want to pull all those private create methods out soon anyway and it is probably best done there.
