### ISSUE TITLE
PanDB search date range

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#446]
Need to add the ability to search a date range, mostly for PanFileDB. See for example #442

**Comment by jamessynge** [comment]
I was thinking something similar as I was reviewing the database code and uses of PanDB throughout POCS. I noticed that there is some access into the guts of PanMongoDB to read from the collections.

**Comment by wtgee** [comment]
>  I noticed that there is some access into the guts of PanMongoDB to read from the collections.
 
You mean outside of the PanDB abstraction? I added a quick fix in the `plot_weather.py` script the other day but thought I had removed all the rest of them.

**Comment by wtgee** [comment]
We don't do any date search on the local data and it's not clear it would be needed. Closing as stale.
