### ISSUE TITLE
Set up Wiki page for metadata to be stored with data

### ISSUE THREAD

**Issue by joshwalawender** [panoptes/POCS#49]
We need to compile a master list of meta data to be stored in each raw image and in each "postage stamp cube" generated from an image sequence.  A wiki page where people can contribute to the list seems like the right place for now.

See also #42 .

**Comment by wtgee** [comment]
Closed with https://github.com/panoptes/PIAA/wiki/Metadata-for-Images-and-Postage-Stamp-Cubes
