### ISSUE TITLE
Consider whether we can use overlayfs for testing

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#520]
Overlayfs allows one to layer one filesystem (directory tree) on top of another (or others). This includes overlaying an empty directory over one that you don't want modified. As a result, one can create a hermetic environment for tests, where all the changes get made to the top filesystem, including edits and deletes of files that are actually in the lower filesystem(s). Docker makes use of this via overlayfs2, IIUC.

This could be useful for testing of POCS, including of scripts such as installation scripts, that would otherwise "ruin" the testing machine.

**Comment by wtgee** [comment]
Related to #191

**Comment by wtgee** [comment]
Much has changed since these days of yore. Closing as stale. Please open new issue as required.
