### ISSUE TITLE
Beginner, where to start ?

### ISSUE THREAD

**Issue by gnthibault** [panoptes/POCS#533]
Dear Panoptes developper.
I recently discovered Panoptes, and it looks like an awesome project (I am an amateur astronomer).
However, it is not that easy for me to understand how to use it, if I don't want to build the exact same setup  described in the hardware section.

Especially, as I already started to work on a project that somehow looks similar to panoptes, using astroplan/astropy/indi/astrometry.net, I would like to try a step by step integration with panoptes, starting with the state machine mechanism.

I did not found inside the jupyter notebook directory of the repository such examples, although the text from the website described exactly what I was looking for: http://projectpanoptes.org/POCS/#statemachine

As a concrete first example, I would like to create a simple panoptes-like statemachine with imaging/slewing/parking/... states that prints out it status and what triggered the change of state, and eventually implement my own weather station class, using for instance weather underground service, or the most common features from the indi API for weather stations.

Thank you very much for your help, and I wish a long life to this wonderful project.

**Comment by AnthonyHorton** [comment]
Hi Thibault, there is a Project PANOPTES forum here: https://forum.projectpanoptes.org/
