### ISSUE TITLE
missing import in setup script ?

### ISSUE THREAD

**Issue by gnthibault** [panoptes/POCS#534]
Edit: Sorry the title of the issue does not really reflects the problem.
Edit2: had the same problem with pymongo

Here is what I got after installing panoptes (python setup.py build install):

```
from pocs.state.machine import PanStateMachine

~/anaconda3/lib/python3.6/site-packages/pocs-0.6.0-py3.6.egg/pocs/state/machine.py in <module>()
      2 import yaml
      3 
----> 4 from transitions import State
      5 
      6 from pocs.utils import error

ModuleNotFoundError: No module named 'transitions'
```

pip install transitions pymongo
solved the problem, but I think it should be included somwhere as a dependancy in the setup.py, no ?

**Comment by AnthonyHorton** [comment]
Did you run the `install-dependencies.sh` script first (as mentioned in the README, https://github.com/panoptes/POCS/blob/develop/README.md)? Both `transitions` and `pymongo` are in the `requirements.txt` file so should have been installed by that script.

**Comment by gnthibault** [comment]
Nop, my bad, sorry

**Comment by AnthonyHorton** [comment]
Not necessarily a non issue. That script is really for Debian based Linux (e.g. Ubuntu), which some users might not be using. We do have some instructions for OS X in the wiki though, which does include the `pip install -r requirements.txt` alternative: https://github.com/panoptes/POCS/wiki/Mac-OSX-Development-Install

**Comment by wtgee** [comment]
Hi @gnthibault , thanks for jumping in!

@AnthonyHorton is right that you should run `pip install -r requirements.txt` first. This is a current mis-match between a pure `setup.py` install and a `pip install` that we want to resolve one day.

I'll address your other questions over in #533.
