### ISSUE TITLE
Incorporate weather into Scheduler

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#54]
The `Scheduler` (which is an astroplan `Observer`) can use the temperature and humidity values for more accurate pointing. Might not be needed.

**Comment by joshwalawender** [comment]
@wtgee I'm not sure I understand the issue, can you elaborate?  You want the scheduler to take temp and humidity as inputs?  Is there any particular reason?  With our pixel scale, these will be negligible effects on pointing.

**Comment by wtgee** [comment]
Let' just close the issue then. I was cleaning up old code and had a commented line in there to add them in so I just created an issue for it so I could remove the line.
