### ISSUE TITLE
Adjust pocs.sleep to more accurately measure time

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#562]
It doesn't account for the amount of time that elapses during calls to self.status() and self.check_messages(), which can take a non-negligible amount of time. Nor does it test how long time.sleep actually slept for.

It should be adjusted or replaced with a method that supports waiting for some maximum amount of time, while performing periodic checks (including a callback to a provided function) and periodic calls to update the status of POCS (i.e. to send a message to the STATUS channel). This would provide us with a uniform method of waiting for events.

**Comment by wtgee** [comment]
Stale. We use the `CountdownTimer` now.
