### ISSUE TITLE
dispatch scheduler question

### ISSUE THREAD

**Issue by gnthibault** [panoptes/POCS#629]
Dear all,

I am still playing with POCS, and I recently came across a line of code that I suspect might generate a bug.
However, I am sorry, I don't have enough time to write a proper test to make it fail consistently.

Here: https://github.com/panoptes/POCS/blob/develop/pocs/scheduler/dispatch.py#L92

I think you should be inserting a tuple instead of just an observation:

`best_obs.insert(0, (self.current_observation.name, self.current_observation.merit))
`
Sorry if I am wrong

I wish you a good day

**Comment by wtgee** [comment]
Hi @gnthibault, thanks for pointing this out! You are right that it should be a tuple that is being inserted and i have made a fix to make it consistent. This was not being used for operating our units but potentially could be by someone, so I appreciate it.

Cheers!

**Comment by gnthibault** [comment]
You are most welcome! I modified the dispatch class in order to use it, and I might have some other correction to report.

If you have a bit of time, I have two questions regarding pocs:

- What version of astroplan are you using (I ambusing the latest one, and it does not look fully compatible with pocs)
- Are you actually uing astroplan scheduling capability in your own scheduler implementation (I am curious)

I wanted to use astroplan scheduling capability, but it looks like this dispatch class is enough for my constraints, and what I need to do right now.

Thank you.

**Comment by jamessynge** [comment]
Thanks again for the fix. We use the latest version of astroplan (i.e.
requirements.txt just says "astroplan" with no version constraint). @wtgee
can address the question about whether/how we are using astroplan.
