### ISSUE TITLE
exp_time vs exptime consistency

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#631]
We currently use both `exp_time` and `exptime` as a variable name in different places. For clarity we should pick one and always use it.

Unless there is a good reason otherwise let's start using `exptime`.

**Comment by AnthonyHorton** [comment]
`EXPTIME` is the most common form for FITS headers so using `exptime` in our code makes sense.  On the other hand `exp_time` is more in keeping with Python conventions for variable names. 3rd option, replacing them all with `exposure` instead! As its one word there's no question about whether it should have underscores or not.  `EXPOSURE` is also an accepted FITS header keyword, albeit in less common usage.

**Comment by ImmortalRabbit** [comment]
> `EXPTIME` is the most common form for FITS headers so using `exptime` in our code makes sense. On the other hand `exp_time` is more in keeping with Python conventions for variable names. 3rd option, replacing them all with `exposure` instead! As its one word there's no question about whether it should have underscores or not. `EXPOSURE` is also an accepted FITS header keyword, albeit in less common usage.

Can I try to solve this issue? I am planning to replace EXPTIME to EXPOSUE and exptime, exp_time to exposure. Do you think that it will solve this issue?
