### ISSUE TITLE
Remove system exit option from PanError

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#676]
https://github.com/panoptes/POCS/pull/672#discussion_r222865623

**Comment by kmeagle1515** [comment]
@wtgee This is not an imp issue though i don't understand why that option is to be removed?

**Comment by wtgee** [comment]
I'm having a hard time figuring out what the comment and Issue was in reference to as well. Or, rather, what the actual problem is. @jamessynge any insight?

**Comment by wtgee** [comment]
`PanError` no longer exits by default although it does have the option. The option has been changed to `False` for all errors. Closing as stale

https://github.com/panoptes/panoptes-utils/blob/3263fcc42fe2348cbb87ba7b0d6d0fb8d88e4c14/panoptes/utils/error.py#L9
