### ISSUE TITLE
RuntimeWarnings from test runs

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#703]
I've seen messages like these in the tail of pytest output:

```
/var/panoptes/miniconda/envs/panoptes-env/lib/python3.6/site-packages/astropy/visualization/stretch.py:264: RuntimeWarning: invalid value encountered in log
  np.log(values, out=values)
/var/panoptes/miniconda/envs/panoptes-env/lib/python3.6/site-packages/matplotlib/colors.py:504: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
```

Now that I've committed #701 , we can probably turn warnings into errors and see where they are coming from more precisely. For example, by using `pytest -Werror`.

**Comment by wtgee** [comment]
Closing as stale. Reopen with example if necessary.
