### ISSUE TITLE
Effectively cache astrometry, et al, on travis

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#711]
Builds currently fail if they can't download the astrometry index files. I believe we are making some use of the Travis caching feature, but not enough to prevent this problem.

**Comment by wtgee** [comment]
I have a branch where I started some work on this. I'll see if it's worth pushing.

**Comment by jamessynge** [comment]
Assigning it to you in hopes that your branch has something worthwhile in it. Several recent builds have failed due these problems.

**Comment by jamessynge** [comment]
Alternately, point me to your branch.

**Comment by jamessynge** [comment]
I've made lots of progress on understanding how to set this up (#712), but now am stymied by astrometry.net being offline again. It seems like we should cache critical dependencies in GCS.

FWIW, it appears that I spoiled the cache for #712 with one bad command which then meant that the next build of that PR didn't have a cache to pull from, so needed to read from astrometry.net. I'm going to try to get that PR thing submitted today so that future builds will hopefully be better able to use the travis provided caching facility.

**Comment by wtgee** [comment]
@jamessynge did we ever get anywhere with this?

If anything I am thinking that as we move more toward a docker-based approach it won't be an issue. I know we are also storing a few things in our own storage bucket, which it doesn't appear we are using but which we could.

**Comment by wtgee** [comment]
Made stale by #951. Please re-open a new issue if needed. Thanks!
