### ISSUE TITLE
Remove PANUSER environment variable?

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#719]
This is only used by scripts during the creation of /var/panoptes, during which we want to set the ownership of the directory, but not at any other time. We do use PANUSER in some documentation to guide the user.

We should consider removing it.

**Comment by ImmortalRabbit** [comment]
> Not opposed to removing it if we don't appear to be using it.
If I will decide to fix this issue, will it be enough to properly delete PANUSER variable from POCS and replace with panoptes? Is there anything that in travis-CI also should be fixed or just to change POCS will be enough to this issue?

**Comment by AnthonyHorton** [comment]
@ImmortalRabbit It will take a bit more than just replacing the `PANUSER` environment variable with `panoptes` everywhere. As @wtgee notes there are sometimes cases where user isn't `panoptes`, e.g. in `huntsman-pocs` and, if I recall correctly, when running in Travis CI.  What we would need is an alternative way of setting `PANUSER`, probably in the main config file.

**Comment by wtgee** [comment]
I'm not sure this is realistic or desirable at this point. Closing as stale.

Related to #555
