### ISSUE TITLE
Scheduler - Move Common Properties

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#750]
The dispatch scheduler currently computes some `common_properties` that are shared between all targets so there is not unnecessary re-computation. These should be moved up to the `BaseScheduler`.

**Comment by ImmortalRabbit** [comment]
What if I will just move common_properties to BaseScheduler and will create a method that initializes values of common_properties depends on time that dispatch used. Will this method solve this issue? @wtgee
