### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#77]
Fix/update the ReadTheDocs site so we have accessible documentation. This will also involve checking in the code and could involve making a test for appropriate documentation.

**Comment by jamessynge** [comment]
pocs_shell appears to require PIAA, which requires shapely (py pkg), which requires geos (non-py pkg).

**Comment by wtgee** [comment]
#951 fixed documentation so that it is at least building correctly. Closing this (very old) issue.  Any further documentation items should have their own issue.
