### ISSUE TITLE
Default Ubuntu setup on 18.04 conflicts with using Chrome Remote Desktop

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#792]
18.04 uses Gnome for its session manager **by default**, which makes it very difficult to use Chrome Remote Desktop (CRD) for administering a unit. I ran into this when trying to remotely assist Luc get his NUC setup. We could use the CRD "Request assistance" feature (he sent me a code, allowing me to see his session), but not "Remote access" (i.e. I couldn't just login to the machine unless he requested it).

I like CRD because Google takes care of providing the servers through which the client (i.e. my laptop) finds the remote host (i.e. the PANOPTES unit). The team at Caltech were able to use VNC easily because (somewhat astonishingly) Caltech doesn't by default block outside access to the hosts on its campus network. This isn't true at most locations; e.g. most home (and enterprise and school) routers will have a firewall / network-address-translation (NAT) feature that prevents connections being initiated from outside the home to computers inside the home, which helps greatly reduce the spread of malware.

So, I'm thinking that the "simple" solution for now is to include in the 18.04 installation instructions steps to recommend that the user use Cinnamon rather than Gnome/Unity as the session manager. Longer term, I'd like to investigate:

- A lighter weight Linux distribution (we don't need to be installing Libre Office, for example); my preference would be some Debian based solution as that seems to be very stable.
- Providing a linux package that has as required dependencies all of the linux packages that we need (e.g. git).

@wtgee Your thoughts?

**Comment by wtgee** [comment]
What about just using [Xubuntu](https://xubuntu.org/) or [Lubuntu](https://lubuntu.net/)? They are both lightweight and nice. I think PAN012 is running Xubuntu. Then we are not only still Debian but we are still actually on [official Ubuntu](https://www.ubuntu.com/download/flavours). They still ship with e.g. office applications but would still be considerably lighter.

**Comment by AnthonyHorton** [comment]
Does LightDM have better compatibility than gdm3? While Ubuntu now defaults to using GDM it continues to include LightDM by default so it's easy for the user to switch. Might be an acceptable short term fix.

**Comment by jamessynge** [comment]
@wtgee I'd be happy to try a lighter weight install. I was wondering about using a distribution optimized for running containers or kubernetes, with the idea of pushing towards remote mgmt, but I fear that would be too big a hurdle any time soon. I'll give one of those two (Xubuntu and Lubuntu) a try today.

@AnthonyHorton wrote 

> Does LightDM have better compatibility than gdm3?

Better compatibility with what?

**Comment by AnthonyHorton** [comment]
> > Does LightDM have better compatibility than gdm3?
> 
> Better compatibility with what?

With Chrome Remote Desktop.

**Comment by programatt** [comment]
@jamessynge I have had very good success running a docker environment on stock ubuntu server instances. If people are ok with administration of the devices being on the CLI and eventually going to updates through docker images there's a really nice tool called [watchtower](https://github.com/v2tec/watchtower) that I use. It listens to the docker socket on the host and automatically pulls down new docker container images and restarts services when changes are detected. Can run on a schedule or every X seconds. For os level updates then you can use tools like ansible to run sh scripts against remote hosts. But it really depends on what the project goals are for the admin side.

**Comment by wtgee** [comment]
Should be addressed by #778

**Comment by wtgee** [comment]
Closing as stale.
