### ISSUE TITLE
Update pySerial and deprecated commands

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#809]
pyserial commands like reset_input_buffer( ) and  reset_output_buffer( ) may come in handy.
Maybe there is a need for a new function like clear_buffer ( ) under which these commands will be executed because peas_shell doesn't have one. 

Also i have noticed a line
https://github.com/panoptes/POCS/blob/4ef6e70e0484156c67b5c8178235b2a9987cca58/bin/peas_shell#L210
here flushInput( ) is supported for python versions 2.x the latest commands is reset_input_buffer( ) 
https://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial.reset_input_buffer

_Originally posted by @kmeagle1515 in https://github.com/panoptes/POCS/issues/347#issuecomment-478951014_

**Comment by SMe12435** [comment]
```
def clean_buffer(self):
	    serial_connection = self.environment.serial_readers[relay_info['board']]['reader']

 	    try:
		    serial_connection.ser.reset_input_buffer()
		    serial_connection.write("{},9".format(relay_info['pin']))  #not sure what this line of code does.
	    except Exception as e:
		    print("Unable to reset Input Buffer: ")
		    print(e)

 	    try:
		    serial_connection.ser.reset_output_buffer()
		    serial_connection.write("{},9".format(relay_info['pin']))  #not sure what this line of code does.
	    except Exception as e:
		    print("Unable to reset output buffer: ")
		    print(e)

```

@wtgee As @kmeagle1515 mentioned in #810, we can do something like this.
