### ISSUE TITLE
Installation dependency problems

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#828]
I'm using scripts/install/install-dependencies.sh to setup a NUC with a fresh install of Ubuntu 18.0.04. Two issues so far:

1. astroscrappy needs a C compiler to install (same is probably true later in the install when we get to astrometry). I added `build-essential` to `apt-packages-list.txt` to work around this.
1. `pip install $POCS/requirements.txt` issues a warning that requests is incompatible with the installed version of urllib3. I wasn't able to see any constraint that explained this, but I was able to fix it with this command: `pip install urllib3>=1.24,<1.25`

I'll send a PR.

**Comment by wtgee** [comment]
Should be addressed by #843

**Comment by wtgee** [comment]
Will be closed by #951
