### ISSUE TITLE
Change cfitsio downloads to use FTPS before 20th September 2019

### ISSUE THREAD

**Issue by AnthonyHorton** [panoptes/POCS#833]
Announcement from NASA HEASARC that they will be discontinuing unencrypted FTP on 20th September 2019: https://heasarc.gsfc.nasa.gov/docs/FTPWarning.html

Currently POCS continuous integration and installation scripts download cfitsio via unecrypted FTP. These scripts will need to be changed to use FTPS instead before 20th September.

**Comment by wtgee** [comment]
Fixed in #835
