### ISSUE TITLE
Remove creation of scheduler from Observatory class

### ISSUE THREAD

**Issue by ImmortalRabbit** [panoptes/POCS#836]
**Is your feature request related to a problem? Please describe.**
In order to add dependency injection, creation of scheduler from Observatory class has to be removed.

**Describe the solution you'd like**
I would like to delete creation of scheduler from Observatory class. In order to do that I am willing to delete method _create_scheduler from Observatory class.
Then planning to replace A with B:
A:
```
        self.scheduler = None
        self._create_scheduler()
```
B:
```
       self.scheduler = None 
       
```
**Describe alternatives you've considered**

**Additional context**

**Related Issues/PRs**
If there are any related Issues or PRs list them here:
##### Required by:
@wtgee @jamessynge

**Comment by wtgee** [comment]
@ImmortalRabbit is this the same as #837?
