### ISSUE TITLE
Creation of scheduler outside of Observatory class

### ISSUE THREAD

**Issue by ImmortalRabbit** [panoptes/POCS#837]
**Is your feature request related to a problem? Please describe.**
In order to add dependency injection, creation of scheduler should be done outside of Observatory class.
**Describe the solution you'd like**
I would like to add creation of scheduler outside of Observatory class. In order to do that I am willing to send scheduler into Observatory class as cameras were sent: 
`def __init__(self, cameras=None, scheduler=None, *args, **kwargs):`
or
`def __init__(self, cameras=None, scheduler, *args, **kwargs):`
I am not quiet sure, should I consider situation when scheduler will not be sent to Observatory class. According to my understanding scheduler is just a software and it's not like cameras that can be not attached. 
Then planning to replace A with B:
A:
```
        self.scheduler = None
        self._create_scheduler()
```
B:
```
       self.scheduler = None 
       if scheduler:
            self.logger.info('Creation of the scheduler in the observatory')
            self.scheduler = scheduler
```
**Describe alternatives you've considered**

**Additional context**

**Related Issues/PRs**
If there are any related Issues or PRs list them here:
##### Required by: 

@wtgee @jamessynge

**Comment by wtgee** [comment]
> am not quiet sure, should I consider situation when scheduler will not be sent to Observatory class.

Yes, I think we want to be able to create an Observatory without necessarily specifying a scheduler. As such, you should use the keyword based (i.e. `scheduler=None`) approach in the constructor.

One thing we will need to do is identify the methods inside the `Observatory` that rely on a scheduler and give appropriate warnings (or handle in some other way) if a scheduler is not present.  For example, an observatory cannot `.observe()` without a scheduler so it makes sense to do some checks before allowing that method.

**Comment by ImmortalRabbit** [comment]
> One thing we will need to do is identify the methods inside the `Observatory` that rely on a scheduler and give appropriate warnings (or handle in some other way) if a scheduler is not present. For example, an observatory cannot `.observe()` without a scheduler so it makes sense to do some checks before allowing that method.

```
        if not self.scheduler:
            return dict()
```

Or should I raise error than just empty dictionary? Or empty dictionary will cause an error?

**Comment by jamessynge** [comment]
The simple approach to dealing with _scheduler being None is simply to raise an exception (e.g. pocs.utils.error.NoObservation) if the observe method is called.

I'd convert .scheduler to ._scheduler, and introduce an @property accessor called scheduler which can then raise the NoObservation error if called when _scheduler isn't set.

**Comment by ImmortalRabbit** [comment]
> The simple approach to dealing with _scheduler being None is simply to raise an exception (e.g. pocs.utils.error.NoObservation) if the observe method is called.
> 
> I'd convert .scheduler to ._scheduler, and introduce an @Property accessor called scheduler which can then raise the NoObservation error if called when _scheduler isn't set.

In my pull request #838 I added a new error NoScheduler which appears if scheduler is None. Do you think that will be fine?
