### ISSUE TITLE
download_IERS_A() is blocked for some reason.

### ISSUE THREAD

**Issue by ImmortalRabbit** [panoptes/POCS#844]
**Describe the bug**
I am from Kazakhstan, and I am trying to update astroplan's data and it's upstream is blocked for some reason. I have tried to use vpn and to try to access to upstream page and it was blocked all around world ( at least for my vpn servers ).

**To Reproduce**
1. Run:
```from astroplan import download_IERS_A
download_IERS_A()```

**Expected behavior**
```AstropyWarning: failed to download http://maia.usno.navy.mil/ser7/finals2000A.all and http://toshi.nofs.navy.mil/ser7/finals2000A.all, using local IERS-B: <urlopen error timed out>;<urlopen error timed out>
    ';'.join(err_list))))  # noqa```

**Related Issues**
Please link any related Issues if known.

**Screenshots**
If applicable, add screenshots to help explain your problem.


**Additional context**
It's possible that it was blocked locally (Kazakhstan) and for specific VPN servers.( My guess).
@wtgee @jamessynge

**Comment by wtgee** [comment]
We *think* this has been fixed by various changes to astroplan (> 0.5) and astropy (> 4.0).  Closing for now until the issue resurfaces.
