### ISSUE TITLE
pocs_shell doesn't know about a new changes of Observatory class

### ISSUE THREAD

**Issue by ImmortalRabbit** [panoptes/POCS#872]
**Describe the bug**
Before, we had only create_camera_from_config and pocs_shell used only it, to create Observatory instance. Now it requires create_scheduler_from_config, create_mount_from_config, create_dome_config.

**To Reproduce**
If we will run pocs_shell, it has to show a lot of errors because of wrong Observatory class is done in wrong way. 

**Expected behavior**

**Related Issues**
Please link any related Issues if known.

**Screenshots**

**Additional context**

**Comment by wtgee** [comment]
Note that there is work in #859 where this has been fixed which could feasibly be back-ported.

**Comment by wtgee** [comment]
This has been cleaned up along the way (although maybe just in #951). Closing for now.
