### ISSUE TITLE
Change _create_mount to create_mount_from_config

### ISSUE THREAD

**Issue by ImmortalRabbit** [panoptes/POCS#873]
*<Enter description of change or enhancement here>*
Remove _create_mount and pass mount to the Observatory class.
**Describe the solution you'd like**
I am going to remove _create_mount, and then fix coverage tests that were working with old code and replaced with create_mount_from_config.
**Describe alternatives you've considered**

**Additional context**

**Related Issues/PRs**
If there are any related Issues or PRs list them here:

**Comment by wtgee** [comment]
Closed by #874.
