### ISSUE TITLE
Add instructions for creating the "panoptes" user

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#94]
We need explicit/detailed instructions for setting up the NUC, including creating the "panoptes" user. In particular, info about adding that user to the dialout group (else it has no access to the Arduino's and the USB-to-Serial adapters).
Also info about creating the /var/panoptes directory (must create the astrometry/data subdir, else some tests fail).

**Comment by jamessynge** [comment]
New info: the panoptes user needs to be in the plugdev group, else has no access to the cameras when not logged in via a locally attached monitor & keyboard, including IIUC via the auto-started tmux session.

**Comment by wtgee** [comment]
Closed by #951.  There are other things that need to be done as part of that process, mostly documentation, but new specific Issues should be opened to identify those.
