### ISSUE TITLE
Remove mongo

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#948]
We no longer use mongo for our database storage but instead default to json flat files.  We no longer wish to maintain mongo support as it is just adding extra dependencies that we don't need. 

**Describe the solution you'd like**
Remove mongo from `database.py` and remove all references and usage of mongo. Also strip from the test suite (which will also help with #191).

**Related Issues/PRs**
#191

**Comment by ac-optimus** [comment]
hi, @wtgee I would like to work on this issue. I have a small doubt related to the the mention  `Also stip from  the test suit`.  I can not see any reference to `mongo` in any of the `tests`? Can you please guide me on this?

**Comment by wtgee** [comment]
> hi, @wtgee I would like to work on this issue. I have a small doubt related to the the mention `Also stip from the test suit`. I can not see any reference to `mongo` in any of the `tests`? Can you please guide me on this?

Hi @ac-optimus , thanks for the interest. This has already been done actually and I just hadn't been good about marking the issue. It's not merged yet but is a part of #951.

I'm happy to suggest some other issues.  Are you looking at a GSoC application?

**Comment by ac-optimus** [comment]
@wtgee thank a lot! could you please suggest some issues. I am new to this organisation and would love to contribute. Yes I am also looking at GSOC application, though I was not able to direct myself to the project ideas page. Can you share some information related?

**Comment by wtgee** [comment]
> @wtgee thanks a lot! could you please suggest some issues. I am new to this organisation and would love to contribute. Yes I am also looking at GSOC application, though I was not able to direct myself to the project ideas page. Can you share some related information?

I'll try to update the page later today. It's currently just blank! Thanks for the interest. I'll let you know here when updated as well.

**Comment by wtgee** [comment]
@ac-optimus actually there is some work related to this in our [`panoptes-utils`](https://github.com/panoptes/panoptes-utils/issues/94) repo if you want to take a stab at it.

Just as an FYI, we don't yet know for sure whether we will be selected as a GSoC project (announced Feb. 20).

**Comment by ac-optimus** [comment]
> ~@ac-optimus actually there is some work related to this in our [`panoptes-utils`](https://github.com/panoptes/panoptes-utils/issues/94) repo if you want to take a stab at it.~ Sorry, this will probably be done by the time you read this. :)
> 
> Just as an FYI, we don't yet know for sure whether we will be selected as a GSoC project (announced Feb. 20).

hi @wtgee just saw your message 😅. Can you suggest some other issue that I can try my hands on? 
Yeah, I am aware of that fact but I would still want to contribute!
Thanks
