### ISSUE TITLE
USB Device Path Auto-Detection

### ISSUE THREAD

**Issue by zacharyt20** [panoptes/POCS#955]
**Is your feature request related to a problem? Please describe.**
This feature request is not related to a problem with POCS. It can be challenging for new Linux users to find the device path (ex. ttyUSB0) of a connected USB device, and ideally this could be avoided with automated detection of the device path.

**Describe the solution you'd like**
Have a script that automatically finds the device path and relates it to a bus and device number, possibly updating the config files as well.

**Describe alternatives you've considered**
Detailed documentation of how to manually find device paths from bus and device numbers aimed at guiding new Linux users.

**Comment by wtgee** [comment]
Closed as part of #956
