### ISSUE TITLE
Log to unique filename by program and time

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#96]
Running peas_shell logs to panoptes.log, as does pocs_shell. They should each log to a unique file name.
And it would help debugging if each run created a new file, e.g. with a timestamp in the name.
To make it easier to find the latest log file, create a symlink from <progname>.log to <progname>.<timestamp>.log.

**Comment by wtgee** [comment]
I'm assuming last sentence just means to symlink the timestamped version to `panoptes.log`.

I think with the consolidation of the repos in #107 we might eventually be getting rid of peas_shell. Regardless, I like having the unified log for the two although don't feel too strongly about it. If we keep them separate we should rename to `pocs.log` and `peas.log`.

**Comment by jamessynge** [comment]
I'm planning to work on this soon, where I intend to take an approach based on Google's c++ logger: each execution of program A creates a unique file name containing the name of the program, A, the process id and a timestamp. It also creates or overwrites a symlink A.log to that unique name.

**Comment by wtgee** [comment]
Closed in #145 and release [v0.6.0](https://github.com/panoptes/POCS/releases/tag/v0.6.0)
