### ISSUE TITLE
Startup scripts

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#97]
Create some startup scripts, based off what @jamessynge has put together.

- Ensure astroplan data is updated 
- Mongo started
- Messenger started (zeromq forwarder)
- Website started (PAWS)
- Environment sensing started (PEAS) 

Supersedes #26

**Comment by jamessynge** [comment]
I've written scripts that run at boot of PAN006 which launches tmux as panoptes user with necessary programs running. Will work with you to get those submitted and updated to be general.

**Comment by wtgee** [comment]
I think most of this has been handled by @jamessynge. Closing this issue. Further items should have their own Issue.
